package com.leetcode.solution;

import java.util.HashMap;

//Find the Difference

/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and
 then add one more letter at a random position.

Find the letter that was added in t.*/

/*Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.*/

public class Question389 {

	/*public char findTheDifference(String s, String t){
		HashMap<Character,Integer> sMap = new HashMap<>();
		HashMap<Character,Integer> tMap = new HashMap<>();
		char[] sChar = s.toCharArray();
		char[] tChar = t.toCharArray();
		char[] orgin;
		if(s.length()>t.length()){
			orgin = sChar;
		}else{
			orgin = tChar;
		}
		
		for(int i = 0;i<sChar.length;i++){
			if(sMap.get(sChar[i]) != null){
				sMap.put(sChar[i], sMap.get(sChar[i])+1);
			}else{
				sMap.put(sChar[i], 1);
			}
		}
		for(int i = 0;i<tChar.length;i++){
			if(tMap.get(tChar[i]) != null){
				tMap.put(tChar[i], tMap.get(tChar[i])+1);
			}else{
				tMap.put(tChar[i], 1);
			}
		}
		for(int i = 0;i<orgin.length;i++){
			if(sMap.get(orgin[i]) != tMap.get(orgin[i])){
				return orgin[i];
			}
		}
//		while(true){
//			sMap.get(key)
//		}
		return '0';
	}*/
	
	public static void main(String[] args){
		System.out.println(new Question389().findTheDifference("abcdee", "abcde"));
		System.out.println((char)('a'^0));
	}

	private char findTheDifference(String s, String t) {
		char result = 0;
		for(int i = 0;i<s.length();i++){
			result = (char) (result ^ s.charAt(i));
		}
		for(int i = 0;i<t.length();i++){
			result = (char)(result^ t.charAt(i));
		}
		
		return result;
	}
}
